//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public int ID { get; set; }
        public System.DateTime Datum { get; set; }
        public double Iznos { get; set; }
        public Nullable<int> KupacID { get; set; }
    
        public virtual Kupac Kupac { get; set; }
    }
}
